"use client";

import Link from "next/link";
import { BarChart3, Bell, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardList, FileText, FolderOpen, LayoutDashboard, MessageSquare, Package, Settings, Sparkles, Users } from "lucide-react";

export function ClientDashboard() {
  return <DashboardFrame mode="client"><div className="dashboard-welcome"><div><span>Proyecto #PD-2026-001</span><h1>Hola, Andrea.</h1><p>Aquí puedes seguir el avance sin perderte entre correos.</p></div><button className="button">Completar información <ChevronRight size={16} /></button></div><div className="project-status"><div><span>Estado actual</span><h2>Información pendiente</h2><p>Necesitamos tu logotipo y los datos de contacto definitivos para continuar.</p></div><strong>25%</strong><div className="status-bar"><i /></div><div className="status-steps">{["Solicitud", "Información", "Diseño", "Desarrollo", "Publicación"].map((item, index) => <span className={index < 2 ? "is-active" : ""} key={item}><i />{item}</span>)}</div></div><div className="dashboard-grid"><article><div><FolderOpen size={20} /><span>Archivos</span></div><h3>2 archivos recibidos</h3><p>Manual de marca.pdf · Logo.png</p><button>Ver archivos <ChevronRight size={15} /></button></article><article><div><CircleDollarSign size={20} /><span>Pagos</span></div><h3>Anticipo recibido</h3><p>Saldo pendiente antes de publicación.</p><button>Ver comprobantes <ChevronRight size={15} /></button></article><article><div><MessageSquare size={20} /><span>Comentarios</span></div><h3>Sin comentarios nuevos</h3><p>Centraliza aquí revisiones y aprobaciones.</p><button>Enviar mensaje <ChevronRight size={15} /></button></article></div><div className="empty-panel"><Sparkles size={24} /><div><h3>Tu primera propuesta visual aparecerá aquí.</h3><p>Te avisaremos por correo cuando esté lista para revisión.</p></div></div></DashboardFrame>;
}

export function AdminDashboard() {
  return <DashboardFrame mode="admin"><div className="dashboard-welcome"><div><span>Panel administrativo</span><h1>Vista general.</h1><p>Seguimiento comercial y operativo de Punto Digital.</p></div><button className="button">Nueva cotización</button></div><div className="metric-grid">{[["Prospectos nuevos", "0", Users], ["Cotizaciones activas", "0", FileText], ["Proyectos en curso", "0", ClipboardList], ["Ingresos confirmados", "$0", BarChart3]].map(([label, value, Icon]) => <article key={label as string}><div><Icon size={20} /><span>Últimos 30 días</span></div><strong>{value as string}</strong><p>{label as string}</p></article>)}</div><div className="admin-table"><div className="table-head"><div><h2>Prospectos recientes</h2><p>Configuraciones y solicitudes recibidas</p></div><button>Ver todos</button></div><div className="table-empty"><Users size={28} /><h3>Aún no hay prospectos</h3><p>Las solicitudes del cotizador aparecerán aquí.</p><Link href="/cotizador">Probar el flujo</Link></div></div></DashboardFrame>;
}

function DashboardFrame({ children, mode }: { children: React.ReactNode; mode: "client" | "admin" }) {
  const clientLinks = [[LayoutDashboard, "Resumen"], [ClipboardList, "Mi proyecto"], [FolderOpen, "Archivos"], [CircleDollarSign, "Pagos"], [MessageSquare, "Comentarios"], [Settings, "Cuenta"]] as const;
  const adminLinks = [[LayoutDashboard, "Resumen"], [Users, "Prospectos"], [FileText, "Cotizaciones"], [Package, "Pedidos"], [ClipboardList, "Proyectos"], [Settings, "Productos"]] as const;
  return <main className="dashboard-page"><aside className="dashboard-sidebar"><Link href="/" className="wordmark wordmark--light"><span className="brand-mark"><i /><i /><i /></span><span><strong>Punto<span>.</span></strong> Digital</span></Link><small>{mode === "client" ? "Portal del cliente" : "Administración"}</small><nav>{(mode === "client" ? clientLinks : adminLinks).map(([Icon, label], index) => <button className={index === 0 ? "is-active" : ""} key={label}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-help"><CheckCircle2 size={20} /><strong>¿Necesitas ayuda?</strong><p>Escríbenos y te respondemos en horario laboral.</p><button>Contactar</button></div></aside><section className="dashboard-main"><header><div><span className="status-dot" /> Todo funcionando</div><div><button aria-label="Notificaciones"><Bell size={18} /></button><div className="user-avatar">AD</div></div></header>{children}</section></main>;
}
