"use client";

import Link from "next/link";
import { BarChart3, Bell, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardList, FileText, FolderOpen, LayoutDashboard, MessageSquare, Package, Settings, Sparkles, Users } from "lucide-react";

export function ClientDashboard({ userName }: { userName: string }) {
  return <DashboardFrame mode="client" userName={userName}><div className="dashboard-welcome"><div><span>Vista preliminar protegida</span><h1>Hola, {userName}.</h1><p>La autorización por proyecto debe conectarse antes de mostrar información real.</p></div><button className="button" disabled>Completar información <ChevronRight size={16} /></button></div><div className="project-status"><div><span>Estado del portal</span><h2>Integración pendiente</h2><p>Esta superficie no consulta proyectos, archivos ni pagos hasta que exista una relación de acceso validada en servidor.</p></div><strong>Demo</strong><div className="status-bar"><i /></div><div className="status-steps">{["Solicitud", "Información", "Diseño", "Desarrollo", "Publicación"].map((item) => <span key={item}><i />{item}</span>)}</div></div><div className="dashboard-grid"><article><div><FolderOpen size={20} /><span>Archivos</span></div><h3>Sin datos conectados</h3><p>La lectura requiere validar pertenencia al proyecto.</p><button disabled>Ver archivos <ChevronRight size={15} /></button></article><article><div><CircleDollarSign size={20} /><span>Pagos</span></div><h3>Sin datos conectados</h3><p>Los pagos solo aparecerán tras confirmación server-side.</p><button disabled>Ver comprobantes <ChevronRight size={15} /></button></article><article><div><MessageSquare size={20} /><span>Comentarios</span></div><h3>Sin datos conectados</h3><p>Los comentarios requerirán autorización por proyecto.</p><button disabled>Enviar mensaje <ChevronRight size={15} /></button></article></div><div className="empty-panel"><Sparkles size={24} /><div><h3>Portal listo para conectar datos autorizados.</h3><p>No se muestran datos inventados ni información de otros clientes.</p></div></div></DashboardFrame>;
}

export function AdminDashboard({ userName }: { userName: string }) {
  return <DashboardFrame mode="admin" userName={userName}><div className="dashboard-welcome"><div><span>Panel administrativo protegido</span><h1>Vista general.</h1><p>La conexión a datos operativos permanece deshabilitada hasta implementar autorización por recurso.</p></div><button className="button" disabled>Nueva cotización</button></div><div className="metric-grid">{[["Prospectos nuevos", "—", Users], ["Cotizaciones activas", "—", FileText], ["Proyectos en curso", "—", ClipboardList], ["Ingresos confirmados", "—", BarChart3]].map(([label, value, Icon]) => <article key={label as string}><div><Icon size={20} /><span>Sin consulta activa</span></div><strong>{value as string}</strong><p>{label as string}</p></article>)}</div><div className="admin-table"><div className="table-head"><div><h2>Prospectos recientes</h2><p>La lectura de datos todavía no está conectada</p></div><button disabled>Ver todos</button></div><div className="table-empty"><Users size={28} /><h3>Superficie administrativa en espera</h3><p>La autenticación ya limita el acceso; falta implementar roles y permisos sobre cada operación.</p><Link href="/cotizador">Revisar el flujo público</Link></div></div></DashboardFrame>;
}

function DashboardFrame({ children, mode, userName }: { children: React.ReactNode; mode: "client" | "admin"; userName: string }) {
  const clientLinks = [[LayoutDashboard, "Resumen"], [ClipboardList, "Mi proyecto"], [FolderOpen, "Archivos"], [CircleDollarSign, "Pagos"], [MessageSquare, "Comentarios"], [Settings, "Cuenta"]] as const;
  const adminLinks = [[LayoutDashboard, "Resumen"], [Users, "Prospectos"], [FileText, "Cotizaciones"], [Package, "Pedidos"], [ClipboardList, "Proyectos"], [Settings, "Productos"]] as const;
  const initials = userName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "PD";
  return <main className="dashboard-page"><aside className="dashboard-sidebar"><Link href="/" className="wordmark wordmark--light"><span className="brand-mark"><i /><i /><i /></span><span><strong>Punto<span>.</span></strong> Digital</span></Link><small>{mode === "client" ? "Portal del cliente" : "Administración"}</small><nav>{(mode === "client" ? clientLinks : adminLinks).map(([Icon, label], index) => <button className={index === 0 ? "is-active" : ""} key={label} disabled={index !== 0}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-help"><CheckCircle2 size={20} /><strong>Acceso protegido</strong><p>Los datos reales requieren autorización por proyecto y operación.</p><button disabled>Contactar</button></div></aside><section className="dashboard-main"><header><div><span className="status-dot" /> Modo seguro</div><div><button aria-label="Notificaciones" disabled><Bell size={18} /></button><div className="user-avatar" title={userName}>{initials}</div></div></header>{children}</section></main>;
}
