import Link from "next/link";
import { ArrowRight, Check, MessageCircle } from "lucide-react";
import { PRODUCTS, formatMoney } from "@/config/products";
import { ContactForm } from "@/components/contact-form";

type PageData = { eyebrow: string; title: string; description: string; bullets?: string[]; legal?: boolean; contact?: boolean };

const serviceData: Record<string, PageData> = {
  "landing-pages": { eyebrow: "Landing pages", title: "Una página enfocada en una sola decisión.", description: "Presenta tu oferta con claridad y lleva cada visita hacia el contacto, la cita o la compra.", bullets: ["Estrategia de conversión", "Hasta 6 secciones", "WhatsApp y formulario", "SEO inicial", "Responsive y rápida"] },
  "sitios-corporativos": { eyebrow: "Sitios corporativos", title: "Una presencia completa para una empresa que quiere avanzar.", description: "Organizamos servicios, experiencia y argumentos para que tus clientes puedan elegirte con confianza.", bullets: ["Arquitectura de contenido", "Diseño personalizado", "Secciones por servicio", "Analytics", "SEO técnico"] },
  "tiendas-en-linea": { eyebrow: "Tiendas en línea", title: "Una experiencia de compra lista para operar.", description: "Catálogo, carrito, pagos y correos transaccionales reunidos en una tienda clara y confiable.", bullets: ["Catálogo e inventario inicial", "Checkout y pagos", "Cupones", "Envíos", "Capacitación"] },
  "sistemas-web": { eyebrow: "Sistemas web", title: "Herramientas digitales que se adaptan a tu operación.", description: "Portales, usuarios, reservaciones, paneles e integraciones construidos alrededor del flujo real de tu negocio.", bullets: ["Diagnóstico funcional", "Flujos y permisos", "Panel administrativo", "Integraciones", "Arquitectura escalable"] },
  "mantenimiento": { eyebrow: "Mantenimiento", title: "Tu página cuidada, segura y al día.", description: "Nos ocupamos de hosting, respaldos, monitoreo y mejoras para que tú puedas ocuparte de tu negocio.", bullets: ["SSL y monitoreo", "Respaldos", "Soporte técnico", "Ajustes mensuales según plan", "Reportes"] },
};

const pageData: Record<string, PageData> = {
  servicios: { eyebrow: "Servicios", title: "Diseño, tecnología y acompañamiento en un solo punto.", description: "Creamos desde páginas enfocadas hasta sistemas a la medida, siempre con una ruta comercial clara.", bullets: ["Landing pages", "Sitios corporativos", "Tiendas en línea", "Portales y sistemas", "Mantenimiento", "Automatizaciones"] },
  paquetes: { eyebrow: "Paquetes", title: "Un punto de partida claro para cada etapa.", description: "Compara alcance, inversión y tiempos aproximados antes de configurar tu proyecto." },
  proyectos: { eyebrow: "Proyectos conceptuales", title: "Así puede sentirse un negocio cuando su página tiene intención.", description: "Explora direcciones creadas para distintos sectores. Cada ejemplo está identificado como demostración conceptual.", bullets: ["Lexora — despacho jurídico", "Nova Dental — clínica dental", "Brasa Norte — restaurante", "Arista — constructora", "Habita — inmobiliaria", "Áurea — belleza"] },
  proceso: { eyebrow: "Cómo funciona", title: "Un proceso claro reduce la incertidumbre y mejora el resultado.", description: "Conocemos tu negocio, reunimos información, diseñamos, construimos, revisamos y publicamos contigo.", bullets: ["1. Conocemos tu negocio", "2. Reunimos la información", "3. Diseñamos tu propuesta", "4. Construimos y revisamos", "5. Publicamos y acompañamos"] },
  nosotros: { eyebrow: "Punto Digital", title: "Hacemos que los buenos negocios se vean tan profesionales como realmente son.", description: "Punto Digital une estrategia, diseño y tecnología para crear presencias claras, útiles y preparadas para crecer.", bullets: ["Claridad antes que jerga", "Diseño antes que plantilla", "Alcance y costos transparentes", "Acompañamiento después de publicar"] },
  demo: { eyebrow: "Demostraciones", title: "No solo te contamos lo que hacemos. Te dejamos experimentarlo.", description: "Explora dispositivos, industrias y estilos para imaginar una dirección antes de comenzar.", bullets: ["Demostrador por industria", "Vista responsive", "Paletas y estilos", "Construcción modular", "Fallback sin WebGL"] },
  contacto: { eyebrow: "Contacto", title: "Cuéntanos dónde quieres llegar.", description: "No necesitas tener todo resuelto. Comparte el contexto y te ayudaremos a encontrar un punto de partida.", contact: true },
  "aviso-de-privacidad": { eyebrow: "Legal", title: "Aviso de privacidad", description: "Este documento es un borrador informativo pendiente de revisión por un profesional legal.", legal: true },
  terminos: { eyebrow: "Legal", title: "Términos y condiciones", description: "Condiciones generales preliminares para el uso del sitio y contratación de servicios. Pendientes de revisión profesional.", legal: true },
  "politica-de-cancelacion": { eyebrow: "Legal", title: "Política de cancelación", description: "Las cancelaciones se revisan según la etapa, el trabajo realizado y las condiciones de la propuesta firmada. Texto pendiente de revisión profesional.", legal: true },
  "politica-de-reembolsos": { eyebrow: "Legal", title: "Política de reembolsos", description: "Los pagos cubren trabajo reservado o ejecutado. Cualquier reembolso se determina conforme al contrato. Texto pendiente de revisión profesional.", legal: true },
  cookies: { eyebrow: "Legal", title: "Uso de cookies", description: "Utilizamos cookies esenciales y, con consentimiento, medición sin enviar datos sensibles. Texto pendiente de revisión profesional.", legal: true },
};

export function getMarketingData(slug: string[]): PageData | null {
  if (slug[0] === "servicios" && slug[1]) return serviceData[slug[1]] ?? null;
  if (slug[0] === "soluciones" && slug[1]) {
    const industry = slug[1].replaceAll("-", " ");
    return { eyebrow: `Soluciones para ${industry}`, title: `Una página profesional pensada para ${industry}.`, description: "Organizamos la información que tus clientes necesitan para entender tu valor, confiar y dar el siguiente paso.", bullets: ["Mensaje adaptado al sector", "Servicios fáciles de explorar", "Contacto directo", "Diseño responsive", "Base lista para Google"] };
  }
  return pageData[slug.join("/")] ?? null;
}

export function MarketingPage({ data, slug }: { data: PageData; slug: string }) {
  return <main id="contenido" className="inner-page"><section className="inner-hero"><div className="inner-hero-grid" /><div className="eyebrow eyebrow--light"><span /> {data.eyebrow}</div><h1>{data.title}</h1><p>{data.description}</p>{!data.legal && <div><Link className="button button--light" href="/cotizador">Configurar mi página <ArrowRight size={17} /></Link><Link className="text-link text-link--light" href="/contacto"><MessageCircle size={17} /> Hablemos</Link></div>}</section><section className="inner-content">{data.contact ? <div className="contact-layout"><div><span>Hagámoslo simple</span><h2>Un mensaje es suficiente para comenzar.</h2><p>Atendemos proyectos en todo México. El tiempo de respuesta habitual es de un día hábil.</p><a href="mailto:hola@punto-digital.mx">hola@punto-digital.mx</a></div><ContactForm /></div> : data.legal ? <div className="legal-copy"><div className="legal-notice">Pendiente de revisión profesional. No constituye asesoría legal.</div><h2>Principios generales</h2><p>Punto Digital trata únicamente la información necesaria para responder solicitudes, preparar propuestas, procesar contrataciones y prestar los servicios acordados.</p><h2>Responsabilidad y consentimiento</h2><p>Las condiciones definitivas aplicables a cada proyecto se detallarán en su propuesta y contrato. Las comunicaciones comerciales opcionales requerirán consentimiento separado y no estarán marcadas por defecto.</p><h2>Contacto</h2><p>Para ejercer derechos o solicitar aclaraciones escribe a privacidad@punto-digital.mx.</p><small>Última actualización: julio de 2026.</small></div> : slug === "paquetes" ? <div className="simple-pricing">{PRODUCTS.map((product) => <article key={product.slug}><span>{product.eyebrow}</span><h2>{product.name}</h2><strong>{product.price ? formatMoney(product.price) : "Cotización personalizada"}</strong><p>{product.description}</p><ul>{product.features.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><Link href={`/cotizador?paquete=${product.slug}`}>Elegir paquete <ArrowRight size={15} /></Link></article>)}</div> : <div className="content-feature"><div><span>Lo esencial</span><h2>Construido para ayudar a que tu negocio se vea, se entienda y se elija.</h2><p>Definimos el alcance contigo y documentamos cada condición antes de comenzar.</p></div><ul>{data.bullets?.map((bullet) => <li key={bullet}><Check size={18} />{bullet}</li>)}</ul></div>}</section><section className="inner-cta"><h2>El siguiente punto de tu negocio puede empezar hoy.</h2><Link className="button" href="/cotizador">Crear mi propuesta <ArrowRight size={17} /></Link></section></main>;
}
