import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  deletedAt: text("deleted_at"),
};

export const profiles = sqliteTable("profiles", { id: text("id").primaryKey(), email: text("email").notNull(), fullName: text("full_name"), role: text("role").notNull().default("client"), ...timestamps }, (table) => [uniqueIndex("profiles_email_idx").on(table.email)]);
export const leads = sqliteTable("leads", { id: text("id").primaryKey(), email: text("email").notNull(), contactName: text("contact_name").notNull(), phone: text("phone"), businessName: text("business_name").notNull(), industry: text("industry"), projectType: text("project_type"), selectedProduct: text("selected_product"), estimatedTotal: real("estimated_total"), payload: text("payload").notNull(), status: text("status").notNull().default("new"), source: text("source").notNull().default("configurator"), ...timestamps }, (table) => [index("leads_created_idx").on(table.createdAt), index("leads_status_idx").on(table.status)]);
export const businesses = sqliteTable("businesses", { id: text("id").primaryKey(), ownerProfileId: text("owner_profile_id"), name: text("name").notNull(), legalName: text("legal_name"), description: text("description"), city: text("city"), country: text("country").default("México"), ...timestamps });
export const quotes = sqliteTable("quotes", { id: text("id").primaryKey(), leadId: text("lead_id"), businessId: text("business_id"), status: text("status").notNull().default("draft"), subtotal: real("subtotal").notNull().default(0), tax: real("tax").notNull().default(0), total: real("total").notNull().default(0), validUntil: text("valid_until"), ...timestamps }, (table) => [index("quotes_lead_idx").on(table.leadId)]);
export const quoteItems = sqliteTable("quote_items", { id: text("id").primaryKey(), quoteId: text("quote_id").notNull(), itemType: text("item_type").notNull(), itemSlug: text("item_slug").notNull(), description: text("description").notNull(), quantity: integer("quantity").notNull().default(1), unitPrice: real("unit_price").notNull(), total: real("total").notNull(), ...timestamps }, (table) => [index("quote_items_quote_idx").on(table.quoteId)]);
export const products = sqliteTable("products", { id: text("id").primaryKey(), slug: text("slug").notNull(), name: text("name").notNull(), description: text("description").notNull(), basePrice: real("base_price"), depositPercentage: integer("deposit_percentage").notNull().default(50), stripeProductId: text("stripe_product_id"), stripeFullPriceId: text("stripe_full_price_id"), stripeDepositPriceId: text("stripe_deposit_price_id"), isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), displayOrder: integer("display_order").notNull().default(0), ...timestamps }, (table) => [uniqueIndex("products_slug_idx").on(table.slug)]);
export const addons = sqliteTable("addons", { id: text("id").primaryKey(), slug: text("slug").notNull(), name: text("name").notNull(), description: text("description").notNull(), priceType: text("price_type").notNull().default("fixed"), price: real("price").notNull(), stripePriceId: text("stripe_price_id"), isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), ...timestamps }, (table) => [uniqueIndex("addons_slug_idx").on(table.slug)]);
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), quoteId: text("quote_id"), businessId: text("business_id"), customerEmail: text("customer_email").notNull(), status: text("status").notNull().default("pending"), total: real("total").notNull(), depositAmount: real("deposit_amount"), stripeCheckoutSessionId: text("stripe_checkout_session_id"), ...timestamps }, (table) => [index("orders_email_idx").on(table.customerEmail)]);
export const orderItems = sqliteTable("order_items", { id: text("id").primaryKey(), orderId: text("order_id").notNull(), itemSlug: text("item_slug").notNull(), name: text("name").notNull(), amount: real("amount").notNull(), ...timestamps }, (table) => [index("order_items_order_idx").on(table.orderId)]);
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), orderId: text("order_id").notNull(), provider: text("provider").notNull().default("stripe"), providerPaymentId: text("provider_payment_id"), amount: real("amount").notNull(), currency: text("currency").notNull().default("mxn"), status: text("status").notNull(), paidAt: text("paid_at"), ...timestamps }, (table) => [uniqueIndex("payments_provider_idx").on(table.providerPaymentId)]);
export const subscriptions = sqliteTable("subscriptions", { id: text("id").primaryKey(), businessId: text("business_id"), stripeSubscriptionId: text("stripe_subscription_id"), planSlug: text("plan_slug").notNull(), status: text("status").notNull(), currentPeriodEnd: text("current_period_end"), ...timestamps });
export const projects = sqliteTable("projects", { id: text("id").primaryKey(), orderId: text("order_id"), businessId: text("business_id"), name: text("name").notNull(), status: text("status").notNull().default("request_received"), progress: integer("progress").notNull().default(0), targetRange: text("target_range"), ...timestamps }, (table) => [index("projects_status_idx").on(table.status)]);
export const projectMembers = sqliteTable("project_members", { id: text("id").primaryKey(), projectId: text("project_id").notNull(), profileId: text("profile_id").notNull(), role: text("role").notNull(), ...timestamps }, (table) => [uniqueIndex("project_members_unique_idx").on(table.projectId, table.profileId)]);
export const projectUpdates = sqliteTable("project_updates", { id: text("id").primaryKey(), projectId: text("project_id").notNull(), title: text("title").notNull(), body: text("body").notNull(), visibleToClient: integer("visible_to_client", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const projectFiles = sqliteTable("project_files", { id: text("id").primaryKey(), projectId: text("project_id").notNull(), ownerProfileId: text("owner_profile_id"), storageKey: text("storage_key").notNull(), filename: text("filename").notNull(), mimeType: text("mime_type").notNull(), size: integer("size").notNull(), ...timestamps }, (table) => [uniqueIndex("project_files_key_idx").on(table.storageKey)]);
export const onboardingResponses = sqliteTable("onboarding_responses", { id: text("id").primaryKey(), projectId: text("project_id").notNull(), section: text("section").notNull(), payload: text("payload").notNull(), completedAt: text("completed_at"), ...timestamps }, (table) => [uniqueIndex("onboarding_project_section_idx").on(table.projectId, table.section)]);
export const previewConfigs = sqliteTable("preview_configs", { id: text("id").primaryKey(), leadId: text("lead_id"), businessId: text("business_id"), payload: text("payload").notNull(), imageStorageKey: text("image_storage_key"), ...timestamps });
export const contactMessages = sqliteTable("contact_messages", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull(), phone: text("phone"), message: text("message").notNull(), status: text("status").notNull().default("new"), ...timestamps }, (table) => [index("contact_created_idx").on(table.createdAt)]);
export const appointments = sqliteTable("appointments", { id: text("id").primaryKey(), leadId: text("lead_id"), email: text("email").notNull(), scheduledAt: text("scheduled_at").notNull(), status: text("status").notNull().default("scheduled"), ...timestamps });
export const testimonials = sqliteTable("testimonials", { id: text("id").primaryKey(), authorName: text("author_name").notNull(), businessName: text("business_name"), quote: text("quote").notNull(), isPublished: integer("is_published", { mode: "boolean" }).notNull().default(false), ...timestamps });
export const portfolioProjects = sqliteTable("portfolio_projects", { id: text("id").primaryKey(), slug: text("slug").notNull(), name: text("name").notNull(), industry: text("industry").notNull(), description: text("description").notNull(), isConcept: integer("is_concept", { mode: "boolean" }).notNull().default(true), isPublished: integer("is_published", { mode: "boolean" }).notNull().default(false), ...timestamps }, (table) => [uniqueIndex("portfolio_slug_idx").on(table.slug)]);
export const faqItems = sqliteTable("faq_items", { id: text("id").primaryKey(), question: text("question").notNull(), answer: text("answer").notNull(), category: text("category"), displayOrder: integer("display_order").notNull().default(0), isPublished: integer("is_published", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), profileId: text("profile_id"), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), payload: text("payload"), ipHash: text("ip_hash"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (table) => [index("audit_entity_idx").on(table.entityType, table.entityId)]);
export const webhookEvents = sqliteTable("webhook_events", { id: text("id").primaryKey(), provider: text("provider").notNull(), providerEventId: text("provider_event_id").notNull(), type: text("type").notNull(), payloadHash: text("payload_hash"), processedAt: text("processed_at"), status: text("status").notNull().default("received"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (table) => [uniqueIndex("webhook_provider_event_idx").on(table.provider, table.providerEventId)]);
